### PR TITLE
fix(i): Remove unused logging context

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

N/A

## Description

This PR removes the unused context from all logging calls.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
:grin: Controversial - this was deliberately included in the func sigs, so that the logger can include stuff from the context as/when we choose to do so.

I think this should be talked about in discord, to give it increased visibility.

**Comment by jsimnz** [comment]
Agree with @AndrewSisley here, this is rather intentional design choice for the purposes of flexability/future upgradeability. I do actually think there is supposed to be a feature that uses this, but might not be implemented yet.

Basically, we should be able to create a general group of Logger KV Tags, and embed that into the context, so that any future call to the logger, that uses the same context will automatically pickup those tags. 

A usecase for this is things like PeerID, where at the top of the DB initialization, we can embed the PeerID into the context, and gurantee that all logger calls contain it.

```go
ctx := context.Background()
ctx = logger.ContextWithKV(ctx, logger.NewKV("peerID", peer.ID())

// ...

db.ExecRequest(ctx, query) // all logger calls inside of this call stack will print (peerID=QzABC...)
```

--

One such example/usecase for the context

**Comment by nasdf** [comment]
> That only works on a log-line-by-line, if the context is always available certain key values can be appended to all log calls without polluting the core code, for example a user ID could be added to every log line.

I think the unused context is polluting the core code.

**Review by islamaliev — APPROVED** [review]
Looks neat with your change, but address please other comments first

**Pull request closed without merging**
