### PR TITLE
test: Capitalize all integration schema types

### LINKED ISSUE #807: Capitalize types in GraphQL examples to fit convention
By convention, we GraphQL capitalize types. E.g. see examples in https://spec.graphql.org/October2021/ or pretty much any other GraphQL examples on the web. Align defradb examples and documentation with this convention.

### PR DESCRIPTION
**Pull request by jsimnz**
## Relevant issue(s)

Resolves #807 

## Description

This converts all schemas in the integrations folder to follow GQL best practices' where the type name is capitalized and the fields are lowercase.

Do not review commit by commit, as they aren't necessarily logically grouped, as this was a long process and spread over all kinds of copy/pastes, search/replaces, and lots (lots) of regex (cringe).

The *only* things that should be changed throughout the PR is:
A) Capitalization of schema types, and lowercase of fields (this is also represented through queries, mutations, etc)
B)  CIDs - as the schemas are involved in generated the CIDs since the `schemaVersionID` is embedded in the commits.
C) DocKeys - Same reason as above
D) Reordering of *some* request results as the implicit order (dockeys) of various results have changed because of (C).

If any other change is noticed that doesn't fall into those categories, please note it :)

## Tasks

- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).

## How has this been tested?

CI

Specify the platform(s) on which this was tested:
- Ubuntu (WSL2)

### CODE REVIEW

**Comment by shahzadlone** [comment]
Sorry about the hound comments, I was testing it out haha.

**Comment by jsimnz** [comment]
> Sorry about the hound comments, I was testing it out haha.

Lol was wondering about this 😂

**Review by AndrewSisley — APPROVED** [review]
LGTM :)  Thanks Orpheus and John for doing this very boring work item :)

**Comment by orpheuslummis** [comment]
Yes thanks John for picking it up when I ran out of steam with it!!

**Review by shahzadlone — APPROVED** [review]
Thanks for taking care of this @jsimnz and @orpheuslummis

I am sorry @jsimnz you might have to take care of conflicts within `tests/integration/explain/default/with_limit*_test.go`.

Also change detector I noticed fails so that will need to be resolved before merge too.

Giving approval :)

**Pull request merged**
