### PR TITLE
chore: Bump to GoLang v1.21

### LINKED ISSUE #2194: chore: Bump to GoLang v1.21
Bump to GoLang v1.21

### LINKED ISSUE #2196: Update token `ONLY_DEFRADB_REPO_CI_PAT` expired end of 2023 on dev account
This token is expired! Update it on dev account.
[ONLY_DEFRADB_REPO_CI_PAT](https://github.com/settings/personal-access-tokens/682461)

We saw a workflow (`.github/workflows/preview-ami-with-terraform-plan.yml`) failing:
https://github.com/sourcenetwork/defradb/actions/runs/7497512672/job/20411209966?pr=2195

### PR DESCRIPTION
**Pull request by shahzadlone**
## Relevant issue(s)
- Resolves #2194
- Resolves #2196

## Description
- This is a routine version bump of GoLang, the previous bump was done in (https://github.com/sourcenetwork/defradb/pull/1689)
- Also updates the golang version for AWS AMI generation.
- Updated the  `ONLY_DEFRADB_REPO_CI_PAT` token as the terraform build would fail otherwise as the token expired starting of this year.

### CODE REVIEW

**Comment by source-devs** [comment]
#### Terraform Format and Style `success`
#### Terraform Initialization `success`
#### Terraform Validation `success`
#### Terraform Plan `success`

<details>

  <summary>Show Plan</summary>

  ```

  Terraform Plan Output:
data.aws_ami.ami: Reading...
aws_security_group.sg: Refreshing state... [id=sg-03ba6f1f9cd118f43]
data.aws_ami.ami: Read complete after 0s [id=ami-0b436d9dc6b1762be]
aws_instance.instance: Refreshing state... [id=i-087b6a34e288d739d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...


  ```


</details>

***Pushed By: @shahzadlone***
***SHA: `65d72573c51e0ecd9289a92ac536ffa0cba9a164`***

**Review by AndrewSisley — APPROVED** [review]
LGTM :)

**Review by AndrewSisley — CHANGES_REQUESTED** [review]
Actually wait

**Comment by AndrewSisley** [comment]
I wanted to quickly undo my approval sorry - I think this should be merged after the release.  We gain nothing by including this in 0.9, and it is a sudden (and uncommunicated) break from our Go version policy and could be really annoying for some users.

**Comment by shahzadlone** [comment]
> I wanted to quickly undo my approval sorry - I think this should be merged after the release. We gain nothing by including this in 0.9, and it is a sudden (and uncommunicated) break from our Go version policy and could be really annoying for some users.
> 
> Much better to wait until just after 0.9 is cut IMO, is only a day or so to wait.

Thanks for your input, I have a strong disagreement for the following reasons:

1) The release binaries are unaffected regardless of which version is used.

2) Most likely, those who want to build from source, would be using a branch anyway.

3) This break is quite minimal in comparison to other breaking changes we have pushed in this release (which will also be communicated through the similar channels as this one, i.e. commit log message and by updating of documents everywhere).

4) Most importantly, in 2 weeks go is scheduled to release there `v1.22` version. Our next release is going to be roughly in 8 weeks. Now that means users who don't follow (2) and want to build source at that exact release commit, will now be using an "unsupported version of GO" for at least the remaining 6 weeks until we make a new release: `Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release.` https://go.dev/doc/devel/release

**Comment by fredcarle** [comment]
At this stage I'm quite ok with updating to 1.21. To most of our partners, at least to my knowledge, the impact will be negligible as they mostly use pre-compile binaries.

**Comment by source-devs** [comment]
#### Terraform Format and Style `success`
#### Terraform Initialization `success`
#### Terraform Validation `success`
#### Terraform Plan `success`

<details>

  <summary>Show Plan</summary>

  ```

  Terraform Plan Output:
data.aws_ami.ami: Reading...
aws_security_group.sg: Refreshing state... [id=sg-03ba6f1f9cd118f43]
data.aws_ami.ami: Read complete after 0s [id=ami-0b436d9dc6b1762be]
aws_instance.instance: Refreshing state... [id=i-087b6a34e288d739d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...


  ```


</details>

***Pushed By: @shahzadlone***
***SHA: `9b36acdb2f4342a2403c8dd20fb1141cd35595c2`***

**Review by fredcarle — APPROVED** [review]
I'm good with this change :)

**Comment by shahzadlone** [comment]
Discussed on discord, will wait for the release to merge.

**Comment by source-devs** [comment]
#### Terraform Format and Style `success`
#### Terraform Initialization `success`
#### Terraform Validation `success`
#### Terraform Plan `success`

<details>

  <summary>Show Plan</summary>

  ```

  Terraform Plan Output:
data.aws_ami.ami: Reading...
aws_security_group.sg: Refreshing state... [id=sg-03ba6f1f9cd118f43]
data.aws_ami.ami: Read complete after 1s [id=ami-0b436d9dc6b1762be]
aws_instance.instance: Refreshing state... [id=i-087b6a34e288d739d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...


  ```


</details>

***Pushed By: @shahzadlone***
***SHA: `11cc696498f488836a01d1100b2a98e7b96c55d6`***

**Comment by source-devs** [comment]
#### Terraform Format and Style `success`
#### Terraform Initialization `success`
#### Terraform Validation `success`
#### Terraform Plan `success`

<details>

  <summary>Show Plan</summary>

  ```

  Terraform Plan Output:
Acquiring state lock. This may take a few moments...
data.aws_ami.ami: Reading...
aws_security_group.sg: Refreshing state... [id=sg-03ba6f1f9cd118f43]
data.aws_ami.ami: Read complete after 0s [id=ami-0b436d9dc6b1762be]
aws_instance.instance: Refreshing state... [id=i-087b6a34e288d739d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...


  ```


</details>

***Pushed By: @shahzadlone***
***SHA: `bea29e7b8811c8c63ea05f15f53b7f018d1be4c7`***

**Comment by source-devs** [comment]
#### Terraform Format and Style `success`
#### Terraform Initialization `success`
#### Terraform Validation `success`
#### Terraform Plan `success`

<details>

  <summary>Show Plan</summary>

  ```

  Terraform Plan Output:
data.aws_ami.ami: Reading...
aws_security_group.sg: Refreshing state... [id=sg-03ba6f1f9cd118f43]
data.aws_ami.ami: Read complete after 0s [id=ami-0b436d9dc6b1762be]
aws_instance.instance: Refreshing state... [id=i-087b6a34e288d739d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.


  ```


</details>

***Pushed By: @shahzadlone***
***SHA: `2f689437eca54297534d594b5ebf2505c9e6c0fd`***

**Review by AndrewSisley — APPROVED** [review]
0.9 Released, approving :)

**Comment by source-devs** [comment]
#### Terraform Format and Style `success`
#### Terraform Initialization `success`
#### Terraform Validation `success`
#### Terraform Plan `success`

<details>

  <summary>Show Plan</summary>

  ```

  Terraform Plan Output:
data.aws_ami.ami: Reading...
aws_security_group.sg: Refreshing state... [id=sg-03ba6f1f9cd118f43]
data.aws_ami.ami: Read complete after 0s [id=ami-0b436d9dc6b1762be]
aws_instance.instance: Refreshing state... [id=i-087b6a34e288d739d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...


  ```


</details>

***Pushed By: @shahzadlone***
***SHA: `a5b90f62735defee5dac56bba168583089a07b0f`***

**Comment by source-devs** [comment]
#### Terraform Format and Style `success`
#### Terraform Initialization `success`
#### Terraform Validation `success`
#### Terraform Plan `success`

<details>

  <summary>Show Plan</summary>

  ```

  Terraform Plan Output:
data.aws_ami.ami: Reading...
aws_security_group.sg: Refreshing state... [id=sg-03ba6f1f9cd118f43]
data.aws_ami.ami: Read complete after 0s [id=ami-0b436d9dc6b1762be]
aws_instance.instance: Refreshing state... [id=i-087b6a34e288d739d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.


  ```


</details>

***Pushed By: @shahzadlone***
***SHA: `615b9693eea59a9f8e22363cc018cd44198a4d7a`***

**Pull request merged**
