### PR TITLE
ci: Add a separate workflow to run the linter

### LINKED ISSUE #1435: Separate linter so we can disable benchmark flow until it's fixed
Previously linter was part of the benchmark flow...
But benchmarks are flakey...
So until https://github.com/sourcenetwork/defradb/issues/1062 gets resolved
We should turn off benchmark workflow and add a lint only workflow.

### PR DESCRIPTION
**Pull request by shahzadlone**
## Relevant issue(s)
Resolves #1435

## Description
Add a Lint only workflow.

## How has this been tested?
CI on branch of a fork and this PR

### CODE REVIEW

**Comment by AndrewSisley** [comment]
question: Why does this not remove the lint stuff from the lint-then-benchmark workflow?

**Comment by shahzadlone** [comment]
> question: Why does this not remove the lint stuff from the lint-then-benchmark workflow?

That entire workflow file will be disabled after this is merged. I don't want to make changes to that workflow as it will be dead until we fix it (would rather preserve it in the state it used to work in rather than in a changed further broken state).

**Comment by AndrewSisley** [comment]
> > question: Why does this not remove the lint stuff from the lint-then-benchmark workflow?
> 
> That entire workflow file will be disabled after this is merged. I don't want to make changes to that workflow as it will be dead until we fix it (would rather preserve it in the state it used to work rather than in a changed further broken state).

Those are good reasons, cheers for the explanation :)

**Review by AndrewSisley — APPROVED** [review]
LGTM :)

**Pull request merged**
