### PR TITLE
ci: Fix the SSH security issue from AMI scan report

### LINKED ISSUE #1425: Our AWS AMI has security issue with ssh keys found by the scan
**Describe the problem**
The AMI security scanning tool says we have to purge out ssh keys under `/root` and `/home`.

image

### PR DESCRIPTION
**Pull request by shahzadlone**
## Relevant issue(s)
Resolves #1425

## Description
- Shreds the keys in all locations noted in the issue.
- Generated the AMI of name: `source-defradb-v0.5.0-20230501085514` , with ID: `ami-0814ed8a30589825b`

## How has this been tested?
- Manually tested the commands after sshing into the image, to ensure the work, and manually generated a run.
- The run that generated the AMI successfully can be found here: https://github.com/sourcenetwork/defradb/actions/runs/4849906529/jobs/8642330562?pr=1426

### CODE REVIEW

**Comment by source-devs** [comment]
## Benchmark Results

### Summary
* 0 Benchmarks successfully compared.
* 0 Benchmarks were ✅ Better.
* 0 Benchmarks were ❌ Worse .
* 0 Benchmarks were ✨ Unchanged.


<details>
<summary> ✅ See Better Results...</summary>
<table class='benchstat better'>
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta

<tr><td>&nbsp;
</tbody>
</table>
</details>

<details>
<summary> ❌ See Worse Results...</summary>
<table class='benchstat worse'>
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta

<tr><td>&nbsp;
</tbody>
</table>
</details>

<details>
<summary> ✨ See Unchanged Results...</summary>
<table class='benchstat unchanged'>
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta

<tr><td>&nbsp;
</tbody>
</table>
</details>

<details>
<summary> 🐋 See Full Results...</summary>

</details>

**Comment by source-devs** [comment]
## Benchmark Results

### Summary
* 0 Benchmarks successfully compared.
* 0 Benchmarks were ✅ Better.
* 0 Benchmarks were ❌ Worse .
* 0 Benchmarks were ✨ Unchanged.


<details>
<summary> ✅ See Better Results...</summary>
<table class='benchstat better'>
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta

<tr><td>&nbsp;
</tbody>
</table>
</details>

<details>
<summary> ❌ See Worse Results...</summary>
<table class='benchstat worse'>
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta

<tr><td>&nbsp;
</tbody>
</table>
</details>

<details>
<summary> ✨ See Unchanged Results...</summary>
<table class='benchstat unchanged'>
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta

<tr><td>&nbsp;
</tbody>
</table>
</details>

<details>
<summary> 🐋 See Full Results...</summary>

</details>

**Review by AndrewSisley — APPROVED** [review]
LGTM

**Comment by fredcarle** [comment]
Were the secrets only useful pre open sourcing ?

**Comment by shahzadlone** [comment]
> Were the secrets only useful pre open sourcing ?

The ones where I removed them from yes. But there are a few other places they are used where they are required (for PR commenting, etc.)

**Pull request merged**
