### PR TITLE
refactor: Remove redundant txn param from fetcher start

### LINKED ISSUE #1623: Remove `txn` param from Fetcher.Start
As of https://github.com/sourcenetwork/defradb/pull/1564 it should be taken from the `Init` call.

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1623

## Description

Removes the redundant txn param from fetcher start as it is always the same value as fetcher.Init

### CODE REVIEW

**Review by fredcarle — APPROVED** [review]
LGTM.

It seems that a more appropriate name for the PR would be `Move txn from fetcher start to init` don't you think?

**Comment by AndrewSisley** [comment]
> LGTM.
> 
> It seems that a more appropriate name for the PR would be `Move txn from fetcher start to init` don't you think?

I disagree with you on that :)  Your suggestion suggests it doesnt already exist on init

**Comment by fredcarle** [comment]
> > LGTM.
> > It seems that a more appropriate name for the PR would be `Move txn from fetcher start to init` don't you think?
> 
> I disagree with you on that :) Your suggestion suggests it doesnt already exist on init

That's my point. It didn't.

**Comment by fredcarle** [comment]
I mean the it was part of the Init param but nothing was done with it.

**Comment by AndrewSisley** [comment]
> That's my point. It didn't.

I think you are mistaken.  It was added to Init in an earlier Lens PR.

**Pull request merged**
