### PR TITLE
feat: Enable playground in Docker build

### LINKED ISSUE #1983: Enable playground in Docker image
Distributing the playground with the DefraDB Docker image will make it the simplest way for new users to try out DefraDB.

- Start DefraDB: `docker run -p 9181:9181 sourcenetwork/defradb start --url 0.0.0.0:9181`
- Navigate browser to `http://localhost:9181`

### PR DESCRIPTION
**Pull request by nasdf**
## Relevant issue(s)

Resolves #1983

## Description

This PR enables the embedded playground in the DefraDB Docker builds.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

Built and pushed image to `docker.io/sourcenetwork/defradb:develop`

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by AndrewSisley — APPROVED** [review]
LGTM - are there any downsides to including this?

**Review by shahzadlone — APPROVED** [review]
LGTM.

question: Out of scope of this PR, but often times when I see the playground dependencies being bumped (non-go deps) I wonder if the tests or some aspect in the build would catch if a dependency broke the playground stuff. Is there a way to (if we don't already) run these tests in ci to ensure playground state isn't broken. Does this PR in anyway improve that situation?

**Comment by nasdf** [comment]
> LGTM - are there any downsides to including this?

Just an increase in size and an extra Docker build step.

**Comment by nasdf** [comment]
> LGTM.
> 
> question: Out of scope of this PR, but often times when I see the playground dependencies being bumped (non-go deps) I wonder if the tests or some aspect in the build would catch if a dependency broke the playground stuff. Is there a way to (if we don't already) run these tests in ci to ensure playground state isn't broken. Does this PR in anyway improve that situation?

It should let us know if the playground build is failing in the Docker build workflow. It would be nice to automate a test that runs the Docker container and loads the playground.

**Pull request merged**
