### PR TITLE
fix: Change the WriteSyncer to use lock when piping

### LINKED ISSUE #1607: Using pipe for logger in tests can result in a race condition
Using pipe for logger in tests can result in a race condition if multiple go routines call a log function.

### PR DESCRIPTION
**Pull request by fredcarle**
## Relevant issue(s)

Resolves #1607

## Description

This PR wraps the pipe WriteSyncer with a Lock so that is can be used concurrently.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [x] I made sure the repository-held documentation is changed accordingly.
- [x] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [x] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

make test

Specify the platform(s) on which this was tested:
- MacOS

### CODE REVIEW

**Review by AndrewSisley — APPROVED** [review]
LGTM, although I cant really review other than by reading the zap-docs, which I assume you have already done :)  Nice find and fix :)

**Comment by fredcarle** [comment]
> LGTM, although I cant really review other than by reading the zap-docs, which I assume you have already done :) Nice find and fix :)

Thank Andy. Yes I tested it with Islam's PR and it solves the issue. Found the fix when I landed on this: https://github.com/uber-go/zap/pull/106

**Review by shahzadlone — APPROVED** [review]
LGTM

**Review by shahzadlone — APPROVED** [review]
LGTM

**Pull request merged**
