### PR TITLE
chore: Document collection.txn

### LINKED ISSUE #1268: Document db.collection.txn
A couple of us misused this recently and it should be documented

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1268

## Description

Documents collection.txn, via use of the Optional type, and code-comment.

A couple of us recently misused this, and these changes should make it harder to do so.

### CODE REVIEW

**Review by shahzadlone — APPROVED** [review]
Would prefer a slightly more descriptive commit title like:
`chore: Document collection.txn by making it optional`

**Comment by AndrewSisley** [comment]
> Would prefer a slightly more descriptive pr title like: `chore: Document collection.txn by making it optional`

Ahhh, wouldnt be fully correct then as I didnt just change the type :)

**Comment by shahzadlone** [comment]
> > Would prefer a slightly more descriptive pr title like: `chore: Document collection.txn by making it optional`
> 
> Ahhh, wouldnt be fully correct then as I didnt just change the type :)

What else was done in this PR, everything does seem like it was due to the type change.

**Comment by AndrewSisley** [comment]
> > > Would prefer a slightly more descriptive pr title like: `chore: Document collection.txn by making it optional`
> > 
> > 
> > Ahhh, wouldnt be fully correct then as I didnt just change the type :)
> 
> What else was done in this PR, everything does seem like it was due to the type change.

I documented it, unless that commit has not been pushed

**Review by fredcarle — APPROVED** [review]
LGTM.

**Pull request merged**
