### PR TITLE
docs: Update discord link

### LINKED ISSUE #3236: Broken discord link in `CONTRIBUTING.md`
**Describe the problem**
The discord link in `CONTRIBUTING.md` does not have `https://` in it so clicking on it, will make GitHub to interpret it as an internal repository link.

**To Reproduce**
Visit  `CONTRIBUTING.md` and click on the discord link.

**Expected behavior**
Opening discord.

**Platform**

**Additional context**
Image

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
## Relevant issue(s)

Resolves #3236

## Description

Small PR - adds `https://` to the Discord link to prevent GitHub from interpreting it as an internal repository link.

## Tasks

- [x] I made sure the code is well commented, particularly hard-to-understand areas.
- [ ] I made sure the repository-held documentation is changed accordingly.
- [ ] I made sure the pull request title adheres to the conventional commit style (the subset used in the project can be found in [tools/configs/chglog/config.yml](tools/configs/chglog/config.yml)).
- [ ] I made sure to discuss its limitations such as threats to validity, vulnerability to mistake and misuse, robustness to invalidation of assumptions, resource requirements, ...

## How has this been tested?

(*replace*) Describe the tests performed to verify the changes. Provide instructions to reproduce them.

Specify the platform(s) on which this was tested:
- *(modify the list accordingly*)
- Arch Linux
- Debian Linux
- MacOS
- Windows

### CODE REVIEW

**Comment by shahzadlone** [comment]
Did you encounter any issues with the current link being interpreted as an internal repository link? 

When I click the discord icon it opens in a tab redirected to: `https://discord.com/invite/w7jYQVJ`

**Comment by emmanuel-ferdman** [comment]
Yes, here how it looks on my side:
image

image

**Comment by shahzadlone** [comment]
@emmanuel-ferdman Thanks for the explanation. 

Two requests for you:

1) Please change the PR title to being with `docs:` so something like: `docs: Update discord link`
2) Please make an issue and link it in the description (right after where it says `Resolves #` is fine)

**Comment by emmanuel-ferdman** [comment]
@shahzadlone done

**Comment by shahzadlone** [comment]
> @shahzadlone done

The `u` in update needs to be a capital.

**Review by shahzadlone — APPROVED** [review]

**Pull request merged**
