### PR TITLE
ci: Allow CI to work from forked repo

### LINKED ISSUE #1391: CodeCov workflow fails from fork
Workflow currently requires secret, although I believe this is no longer required by code cov as we are open source now

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #1391

## Description

Removes code cov token from the code cov workflow, and changes the tests workflows to run on pull request.

### CODE REVIEW

**Comment by shahzadlone** [comment]
Just ensure we can see it upload the test coverage properly and it shows coverage on codecov for this PR.

**Comment by AndrewSisley** [comment]
> Just ensure we can see it upload the test coverage properly and it shows coverage on codecov for this PR.

Of course, there is currently an issue with reporting to the source repo from a fork though - workflow run is here: https://github.com/AndrewSisley/defradb/actions/runs/4768767655/jobs/8478466809

The other PR that also ran that flow successfully has not yet added it to the PR yet though :(

**Comment by shahzadlone** [comment]
I think it's because adding/changing workflows through PRs have no affect on pull_request.synchronize or the other pull_request types until workflow has been merged into at least base branch.

So for changes like these probably hunch is that for security purposes we are forced to use non-forked branches, and have the change tested and merged. Then see if your normal forked branches work as expected.

**Review by fredcarle — APPROVED** [review]

**Review by shahzadlone — APPROVED** [review]
LGTM

**Pull request merged**
